### ISSUE TITLE
Zap crashes right after scanning QR code/entering PIN

### ISSUE THREAD

**Issue by Kixunil** [LN-Zap/zap-android#30] opened 2019-06-11 07:23 UTC
I've submitted this via "Feedback" feature of Android, but I'd like to give a more detailed information here as well as have bidirectional communication.

Description of the issue
------------------------------

When the QR code is scanned, the application crashes immediately. After re-opening and entering the PIN, it crashes again.

Environment
----------------

Phone: Google Pixel 3
Android version: 9
QR code created using shell as described here: https://github.com/LN-Zap/lndconnect/pull/15

Steps to reproduce
-------------------------

1. Install the application
2. Create a wallet
3. Scan the QR code
4. Observe a crash
5. Re-launch
6. Enter the valid PIN
7. Observe a crash

Expected behavior
------------------------

Application connects to the node. In case the link in QR code is broken, then the user is informed about it, ideally with description of what is broken.

**Comment by michaelWuensch** [comment] 2019-06-11 17:05
Hi, thanks for reporting.
I will have a look at it.
In the meantime you can help me by answering some questions:
- What version is your LND?
- Did you get it running with a lnd connect string created with a different approach than you described?
- Are you sure the string you copied follows this scheme: 
  _lndconnect://[host]:[port]?cert=[base64url  certifcate]&macaroon=[base64url macaroon]_
- Does your String contain all of the above parts, or does it ommit the port for example?

**Comment by michaelWuensch** [comment] 2019-06-12 06:35
From what I can see from your PR you linked to, you have this format:

lndconnect://example.com?cert=...

The port is missing here.
Anyway if this is the reason, I still have to make better error handling. The App should of course not crash.

**Comment by Kixunil** [comment] 2019-06-12 09:20
* 0.6.0-beta 
* I didn't since I wanted to avoid dependencies
* Yes I'm sure
* I tried with both port omitted and not omitted. It crashes in both cases.

**Comment by michaelWuensch** [comment] 2019-06-14 06:33
Hi,
I was able to reproduce this.
The way you created your connect string encodes the tls and macaroon in Base64 while lndconnect encodes in Base64URL.
We only support the format from lndconnect.
I will try to make better error handling though instead of crashing the app. :)

**Comment by michaelWuensch** [comment] 2019-06-14 07:42
3b7a81bcd0c94e86291d7db72e14e3fceabe562c
I fixed the error handling.
Now you get a "Invalid connection information" message when trying to scan your qr code instead of an app crash. 
The fix will be in the next update.
Please note that you unfortunately have to uninstall and reinstall your app to initiate a new connection, as it now has saved the "corrupt" data and will always crash on reading it.

**Closed by michaelWuensch** 2019-06-14 07:42 UTC

**Comment by Kixunil** [comment] 2019-06-16 13:49
I missed the distinction between URL and non-URL. It's so small thing...

FYI, it's possible to remove application data in settings instead of reistalling the application.

Thanks for help!
