### ISSUE TITLE
Play Store links broken

### ISSUE THREAD

**Issue by yeru83** [LN-Zap/zap-android#321] opened 2021-05-04 08:19 UTC
## Description
Following links such as https://play.google.com/store/apps/details?id=zapsolutions.zap 
from 
https://zaphq.io/ 
leads to a "Not Found" error on Google Play. 

## Expected Behavior

https://play.google.com/store/apps/details?id=zapsolutions.zap should get to the app download page.

https://zaphq.io/ should point to a working download page.

Searching "zap wallet" in Play Store should get to a working download link.
## Actual Behavior

These urls just ain't workin'. 

## Your Environment

https://play.google.com/store/apps/developer?id=Zap

**Comment by michaelWuensch** [comment] 2021-05-22 16:10
Hi there,
I cannot reproduce this. On my PC and on my Smartphone it works as expected and the links are not broken.
Have you tried it with your smartphone? Maybe it is unavailable as your smartphone does not have the minimum required Android version (Android 6.0 - Marshmallow).

**Comment by michaelWuensch** [comment] 2021-07-17 15:40
All the links you provided above work on my end.
I am closing this issue now as I am not able to reproduce this nor any other person mentioned this.
Feel free to reopen this issue if it still persists for you or if you have more information.

**Closed by michaelWuensch** 2021-07-17 15:40 UTC
