### ISSUE TITLE
Balance not updated after LNURL withdraw

### ISSUE THREAD

**Issue by kiwiidb** [LN-Zap/zap-android#322] opened 2021-05-23 09:17 UTC
## Description
After a succesful lnurl-withdraw, the balance on the home screen is not updated.

## Expected Behavior
Balance on the home screen reflecting the new balance after lnurl withdraw.

## Actual Behavior

Balance on the home screen reflecting outdated balance after lnurl-witdhraw

## Steps to Reproduce

1. LNURL withdraw.
2. Inspect balance on home screen
3.
4.

## Your Environment

- Zap version: _0.4.1-beta_

**Comment by michaelWuensch** [comment] 2021-07-02 16:54
@kiwiidb 
Thanks for the issue report. I will have a look at it for the next version.

**Comment by michaelWuensch** [comment] 2021-07-18 10:40
@kiwiidb
hi I just tested it and it updated automatically. It took about 1 or 2 seconds after the success screen though. This is because the success screen depends on the answer of the communication between the lnurl service and your node, while the actual updating of the balance is constrained to the actual htlc taking place.
Which version of LND are you running? The automated updating based on htlcs in Zap Android is only available on LND 11.0 and later.

**Comment by michaelWuensch** [comment] 2021-09-30 21:57
I cannot reproduce it and I didn't get an answer which lnd version you used. I am closing the issue now.
If you still have that problem, feel free to reopen the issue.

**Closed by michaelWuensch** 2021-09-30 21:57 UTC
