### ISSUE TITLE
Error unable to find path to destination when in reality there is a path

### ISSUE THREAD

**Issue by Relaxo143** [LN-Zap/zap-android#33] opened 2019-06-13 23:55 UTC
I love the interface of Zap, but it says a payment cannot be made because there's no route. When I tried the exact same invoice with Shango wallet (Another wallet that connects with LND) it went through no problem. Besides, the qr scanner is horrible. It takes ages to recognize a qr code and you have to be very still.

**Comment by michaelWuensch** [comment] 2019-06-14 04:59
Hi, thanks for your report.

Is your Shango App connected to the SAME LND node as Zap? 
Using the same Invoice ensures you have the same destination in the network. But if you have a different starting point it of course have to find another route, which is then not really comparable.

About the QR scanner. It works quite well for me, I guess you are to close, trying to fill the white area. It works a lot better going further away and just have the qr code somewhere inside that area.
Could you try that? If it works, I might try to change the UI somehow to make this more clear / easy to use.

**Comment by Relaxo143** [comment] 2019-06-14 07:50
> Hi, thanks for your report.
> 
> Is your Shango App connected to the SAME LND node as Zap?
> Using the same Invoice ensures you have the same destination in the network. But if you have a different starting point it of course have to find another route, which is then not really comparable.
> 
> About the QR scanner. It works quite well for me, I guess you are to close, trying to fill the white area. It works a lot better going further away and just have the qr code somewhere inside that area.
> Could you try that? If it works, I might try to change the UI somehow to make this more clear / easy to use.

It is the same LND node on the same machine. Both zap and shango show the same balance in sats so I'm sure it's the same node. I don't have any other nodes anyway. I think I tried it both close and further away but I'll see again. Thank you for your amazing work by the way!

**Comment by Relaxo143** [comment] 2019-06-14 08:04
By the way, I tried paying the invoice through the windows desktop zap wallet and it worked. It seems to be a problem with the mobile app.

**Comment by michaelWuensch** [comment] 2019-07-12 21:06
We most likely found the issue and it will be fixed in the next version!

**Comment by Relaxo143** [comment] 2019-07-13 12:21
> We most likely found the issue and it will be fixed in the next version!

Thank you for the great work! What is the actual fee limit? I mean is there a protection so that I don't send 200 sats and pay 10k sats fee?

**Comment by michaelWuensch** [comment] 2019-07-13 13:53
Well we query routs before you send something. This way we can calculate the fees and show the user the expected fee. We then set the maximum fee that was found as fee limit to ensure the user will not pay more than we stated in the beginning.
And the issue was caused by conversion from msats to sats. The limit was therefore actually fractions of a sat to low.

**Comment by JimmyMow** [comment] 2019-07-19 01:41
@Relaxo143, in the end, this was an error in our fee calculation on the network in combination with an error on how to use the LND API. We have pushed an update and this should be resolved now. 

Can you update and confirm?

**Comment by Relaxo143** [comment] 2019-07-19 16:37
> @Relaxo143, in the end, this was an error in our fee calculation on the network in combination with an error on how to use the LND API. We have pushed an update and this should be resolved now.
> 
> Can you update and confirm?

I have updated and for now there are no errors. Though the problem appeared rarely so I can't tell for sure. Time will tell. If I experience the same issue again I will open another one here. Thank you for resolving the problem.

**Closed** 2019-07-19 16:58 UTC
